# pytest.ini
[pytest]
# Testlarni ishga tushirish uchun standart parametrlar:
# -v: Batafsil ma'lumot (verbose)
# -s: Print() qilingan matnlarni konsolda ko'rsatish
# --alluredir: Allure hisobotlari saqlanadigan papka
addopts = -v -s --alluredir=reports/allure-results

# Pytest qaysi papkalardan testlarni qidirishi kerak
testpaths = tests

# Fayl, klass va funksiyalarni nomlash qoidalari (naming conventions)
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Автоматически распознавать и запускать async тесты
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function